# Generated by Django 2.2.1 on 2019-05-23 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askfeedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='askmodel',
            name='deadline',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
